//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sciffer.Erp.Domain.Model
{
    
    using System.ComponentModel.DataAnnotations;

    public  class REF_PAYMENT_TYPE
    {
        [Key]
        public int PAYMENT_TYPE_ID { get; set; }
        [Display(Name ="Payment Type Name")]
        public string PAYMENT_TYPE_NAME { get; set; }
        public bool is_blocked { get; set; }
        public bool is_active { get; set; }
    }
}
