//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sciffer.Erp.Domain.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class REF_COMPANY
    {
      
        [Key]
        public int COMPANY_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_DISPLAY_NAME { get; set; }
        public string REGISTERED_ADDRESS { get; set; }
        public string REGISTERED_CITY { get; set; }
        public int REGISTERED_STATE_ID { get; set; }
        [ForeignKey("REGISTERED_STATE_ID")]
        public virtual REF_STATE REF_STATE { get; set; }
        public double? REGISTERED_TELEPHONE { get; set; }
        public double? REGISTERED_MOBILE { get; set; }
        public string REGISTERED_EMAIL { get; set; }
        public string CORPORATE_ADDRESS { get; set; }
        public string CORPORATE_CITY { get; set; }
        public int CORPORATE_STATE_ID { get; set; }
        [ForeignKey("CORPORATE_STATE_ID")]
        public virtual REF_STATE REF_STATE1 { get; set; }
        public double? CORPORATE_TELEPHONE { get; set; }
        public double? CORPORATE_MOBILE { get; set; }
        public int ORG_TYPE_ID { get; set; }
        [ForeignKey("ORG_TYPE_ID")]
        public virtual REF_ORG_TYPE REF_ORG_TYPE { get; set; }
        public string WEBSITE { get; set; }
        public byte[] LOGO { get; set; }
        public string PAN_NO { get; set; }
        public string CIN_NO { get; set; }
        public string TAN_NO { get; set; }
        public int CURRENCY_ID { get; set; }
        [ForeignKey("CURRENCY_ID")]
        public virtual REF_CURRENCY REF_CURRENCY { get; set; }
        public bool ALLOW_NEGATIVE_CASH { get; set; }
        public bool ALLOW_NEGATIVE_INVENTORY { get; set; }
        public string registered_telephone_code { get; set; }
        public string corporate_telephone_code { get; set; }
        public int? registered_pincode { get; set; }
        public int? corporate_pincode { get; set; }
    }
}
