//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sciffer.Erp.Domain.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class REF_PLANT_ATTRIBUTE
    {
        [Key]
        [Column(Order = 0)]
        public int PLANT_ID { get; set; }
        [ForeignKey("PLANT_ID")]
        public virtual REF_PLANT REF_PLANT { get; set; }


        [Key]
        [Column(Order = 1)]
        public int ATTRIBUTE_ID { get; set; }
        [ForeignKey("ATTRIBUTE_ID")]
        public virtual REF_ATTRIBUTES REF_ATTRIBUTES { get; set; }

        [Display(Name = "Attribute Value")]
        public string ATTRIBUTE_VALUE { get; set; }
    
       
    }
}
