//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sciffer.Erp.Domain.Model
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class REF_PLANT
    {
       [Key]
        public int PLANT_ID { get; set; }
        public string PLANT_NAME { get; set; }
        public string PLANT_CODE { get; set; }
        public string PLANT_ADDRESS { get; set; }
        public string PLANT_CITY { get; set; }
        public int PLANT_STATE { get; set; }
        [ForeignKey("PLANT_STATE")]
        public virtual REF_STATE REF_STATE { get; set; }
        public string PLANT_TELEPHONE { get; set; }
        public string PLANT_MOBILE { get; set; }
        public string PLANT_EMAIL { get; set; }
        public string excise_number { get; set; }
        public string excise_range { get; set; }
        public string excise_division { get; set; }
        public string service_tax_number { get; set; }
        public string excise_commisionerate { get; set; }
        public string vat_number { get; set; }
        public string cst_number { get; set; }
        public string gst_number { get; set; }
        public bool is_active { get; set; }
        public bool is_blocked { get; set; }
        public string pincode { get; set; }
        public string telephone_cdoe { get; set; }
        
    }
}
